### PR TITLE
Test

### PR DESCRIPTION
**Pull request by lubosmj**
[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
What kind of an old container is this running?
It tries tor start rq workers. And then it fails the bindings test.

**Comment by fao89** [comment]
> What kind of an old container is this running?
> It tries tor start rq workers. And then it fails the bindings test.

the fedora image
```
FROM {{ ci_base | default("pulp/pulp-ci:latest") }}
```
https://github.com/pulp/pulp-openapi-generator/blob/master/.ci/ansible/Containerfile.j2#L1

**Comment by mdellweg** [comment]
> the fedora image

We don't build that anymore, right? Should we take it down?

**Comment by fao89** [comment]
I thought we did, but it is still there
https://hub.docker.com/repository/docker/pulp/pulp-ci

**Pull request closed without merging**
