### PR TITLE
Pass --security-opt label=level:$PULP_MCS_LABEL to docker also

### PR DESCRIPTION
**Pull request by dkliban**
[noissue]

### CODE REVIEW

**Comment by gerrod3** [comment]
This did not work on machine using docker.

**Comment by dkliban** [comment]
Closing since this doesn't seem to work

**Review by gerrod3 — APPROVED** [review]
NVM, it does work. :1st_place_medal:

**Review by bmbouter — APPROVED** [review]
This looks right to me.

**Pull request merged**
